version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  build_and_publish:
    jobs:
      - aws-ecr/build-and-push-image:
          context: emkaytec-io-aws
          repo: random-address-generator
          filters:
            branches:
              only: main
